### ISSUE TITLE
Add unit tests for CreateAccount and RecoverAccount methods

### ISSUE THREAD

**Issue by adambabik** [status-im/status-go#510]
# Problem

`./geth/account` package has a poor unit tests coverage which should be improved.

# Implementation

There is only one struct that needs to be tested: `Manager` in `geth/account/accounts.go`. This struct depends on `common.NodeManager` and we'd like to get rid of this dependency, thus, please implement unit tests **only** for methods that do not depend on `common.NodeManager`. Identified methods so far: `CreateAccount` and `RecoverAccount`. 

Unit tests should be put in `geth/account/accounts_test.go` file.

# Acceptance Criteria

1. There are no race conditions,
1. Test coverage for identified methods should be decent (as a reference `VerifyAccountPassword` has 89.7% coverage; something over 80% should be fine but follow common sense :)). 

# Notes

Please follow code styles guidelines: [Effective Go](https://golang.org/doc/effective_go.html) and [CodeReviewComments](https://github.com/golang/go/wiki/CodeReviewComments).

To get a coverage for functions, run:
```
$ go test -coverprofile=coverage.out  ./geth/account/...
$ go tool cover -func=coverage.out
```

**Comment by canercidam** [comment]
Getting a PR ready for this.

**Comment by pablanopete** [comment]
@canercidam thanks for jumping on it so quick! Make sure to ping me @hutch in our riot https://chat.status.im/#/register so we can chat!

**Comment by canercidam** [comment]
@adambabik I don't see how `CreateAccount` and `RecoverAccount` are independent from `common.NodeManager` as they call a dependent function which is `Manager.importExtendedKey` but please review #511 to see if it helps.

**Comment by canercidam** [comment]
I think `accounts.go` requires some rewriting in order to keep all test coverage independent from `common.NodeManager`.

**Comment by b00ris** [comment]
@adambabik I think it's duplicate issue. This issue was solved to https://github.com/status-im/status-go/pull/445.

**Comment by adambabik** [comment]
@canercidam good catch! I totally missed that unexported method. This also makes it ok to write unit tests for other exported methods like `SelectAccount`. However, as it was not in the original scope, it's up to you :)

**Comment by divan** [comment]
@b00ris I'll try to explain here why I don't think the issue has been solved in #445.

Let's consider following schematic representation of a package. Boxes are types and ovals are functions/methods:
![unittesting 001](https://user-images.githubusercontent.com/880202/33989615-641edc86-e0c8-11e7-8e83-b6f6f9b047e3.jpeg)

In a well-designed code, most of the code responsible for logic, calculations, implementing business-logic etc are on the bottom of this tree-like representation — they're small, isolated and used by other functions.

Those are good candidates for unit testing. Testing this code ensures that most important pieces of logic are tested.
![unittesting 004](https://user-images.githubusercontent.com/880202/33989701-b9df25a4-e0c8-11e7-98a0-873c1210e9fe.jpeg)
Upper functions, which are often just "gluing" helpers can be a subject for unit testing as well — there is no single approach here and it really depends on the code. But more often than not those higher functions are a subject for integration testing, not the unit-tests.

What I see in #445 is kind of opposite — small functions at the bottom of the call tree are completely ignored and replaced by mocks. This replacement has the additional cost of breaking down types (and abstractions they represent), introducing new interfaces and complicating codebase. And the then it tests actually mocked versions of gluing code.

![unittesting 002](https://user-images.githubusercontent.com/880202/33989833-3b00df1a-e0c9-11e7-97bd-62b6ea61ff1b.jpeg)
![unittesting 003](https://user-images.githubusercontent.com/880202/33989841-41abecf6-e0c9-11e7-9f20-42c2765098fe.jpeg)

I hope this will help to clarify what is unit testing in this case. Needless to say, that tests need to be designed on the grounds of thorough understanding what's this code is for, use cases and edge cases. So it's not just "increase coverage".

**Comment by JekaMas** [comment]
Why only "leaf" methods are good condidates for unit testing? Is there some research about it? I always think that any method is a good condidate for unit testing, especially in TDD.

**Comment by divan** [comment]
@JekaMas "leaf" methods are isolated and in a properly designed code usually contains "actual" logic. In the context of account package, that might be a function of that looks for a key file on the filesystem or a code that filters constructs eth.accounts() response. Those functions should be small, focused on solving one specific problem and have minimum (ideally, zero) dependencies, except standard library or other code that is known to be well tested. Part of this issue may include extracting those pieces of code from larger functions and making them a separate functions for better unit testing.

I also updated diagram of how that "introducing mocks" approach changes the picture of the package:
![unitests2 004](https://user-images.githubusercontent.com/880202/33992251-265202b6-e0d2-11e7-929c-732263b487a2.jpeg)

**Comment by JekaMas** [comment]
The second question is "mocks" and unit testing with mocks. I think you really need to read https://martinfowler.com/articles/mocksArentStubs.html - this classic article provides quite different meaning of mocks and unit testing than you describe.
I still cant get why only "leaf" methods is good for unit testing. As far as i see this is only your opinion - quite interesting opinion however it's not a law or some well proven by research assemption.

By my opinion: we totally loose our target. Our target is good beta in March and we should deliver issues and code and stop such holy wars. And we should agree there is no right opinion that some of us should understand - all our opinions have a value.

**Comment by divan** [comment]
@JekaMas as for the research — I recommend "How Google tests software" book, it's free and really good read. They call "unit tests" a "small tests", but it's not Google-specific or anything. The term unit is really good fit here — it's a test that tests small "unit" of the program.

**Comment by JekaMas** [comment]
Are we Google? :)

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 500.00
Contract address: [0x8dbffc03792a8496a52d07162f92c89f8fb00ecc](https://etherscan.io/address/0x8dbffc03792a8496a52d07162f92c89f8fb00ecc)
Network: Mainnet
Paid to: canercidam
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.
